# Generated by Django 5.2.6 on 2025-09-29 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('users', '0002_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='saved_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.useraddress'),
        ),
    ]
